interactions:
  - flint_and_steel:
      - ignitemob
  - bucket:
      - milkcow
  - shears:
      - shearsheep
      - breakwithtool
  - wooden_pickaxe:
      - breakwithtool
  - stone_pickaxe:
      - breakwithtool
  - golden_pickaxe:
      - breakwithtool
  - iron_pickaxe:
      - breakwithtool
  - diamond_pickaxe:
      - breakwithtool
  - netherite_pickaxe:
      - breakwithtool
  - wooden_axe:
      - breakwithtool
      - attackwithweapon
  - stone_axe:
      - breakwithtool
      - attackwithweapon
  - golden_axe:
      - breakwithtool
      - attackwithweapon
  - iron_axe:
      - breakwithtool
      - attackwithweapon
  - diamond_axe:
      - breakwithtool
      - attackwithweapon
  - netherite_axe:
      - breakwithtool
      - attackwithweapon
  - wooden_shovel:
      - breakwithtool
  - stone_shovel:
      - breakwithtool
  - golden_shovel:
      - breakwithtool
  - iron_shovel:
      - breakwithtool
  - diamond_shovel:
      - breakwithtool
  - netherite_shovel:
      - breakwithtool
  - wooden_hoe:
      - tillsoil
  - stone_hoe:
      - tillsoil
  - golden_hoe:
      - tillsoil
  - iron_hoe:
      - tillsoil
  - diamond_hoe:
      - tillsoil
  - netherite_hoe:
      - tillsoil
  - wooden_sword:
      - attackwithweapon
  - stone_sword:
      - attackwithweapon
  - golden_sword:
      - attackwithweapon
  - iron_sword:
      - attackwithweapon
  - diamond_sword:
      - attackwithweapon
  - netherite_sword:
      - attackwithweapon
  - oak_sapling:
      - plantcrop
  - spruce_sapling:
      - plantcrop
  - birch_sapling:
      - plantcrop
  - jungle_sapling:
      - plantcrop
  - acacia_sapling:
      - plantcrop
  - dark_oak_sapling:
      - plantcrop
  - wheat_seeds:
      - plantcrop
  - pumpkin_seeds:
      - plantcrop
  - melon_seeds:
      - plantcrop
  - beetroot_seeds:
      - plantcrop
  - potato:
      - plantcrop
  - nether_wart:
      - plantcrop